### ISSUE TITLE
Doesn't show up on sites that use SSL

### ISSUE THREAD

**Issue by thefinn93** [reddit-archive/reddit-companion#12]
There is no reddit companion button on sites that use https. I imagine that this is some chrome security thing, but it'd be nice to have fixed if possible.

**Comment by mhweaver** [comment]
You ever get the [feeling](https://github.com/mhweaver/reddit-companion/commits/https) you can see the future? Once I am sure there aren't any crazy side-effects, I'll do a pull request and see if the reddit gods are want to merge it.

**Comment by thefinn93** [comment]
haha thanks!
