### ISSUE TITLE
Bar showing up embedded within page

### ISSUE THREAD

**Issue by garg** [reddit-archive/reddit-companion#17]
This was a one time issue: Chrome was restarted for an update and when it came back and the tabs restored automatically, the chrome bar appeared in place of an embedded youtube video. Here is the screen shot:

http://imgur.com/58LWd

A refresh fixed it.

**Comment by chromakode** [comment]
Sounds like some form of iframe src corruption. I've seen this happen in Firefox before, but never in Chrome. I'd guess that this is a bug in Chrome. Thanks for reporting this! Please let me know if it happens again or you find a reproduce case.
