### ISSUE TITLE
Disable companion on self posts

### ISSUE THREAD

**Issue by rohandhruva** [reddit-archive/reddit-companion#2]
IMHO, the companion bar is not required when browsing a (sub-)reddit self post. Can we (by default, or) have an option to disable it for those? Thanks!

**Comment by mmaluff** [comment]
I agree, I've been looking into this for the past half an hour or so but I have zero knowledge of java so I'm not really making any progress.

**Comment by chromakode** [comment]
Fixed in 8f93d93a5398cb64a81cd3ecbb3705b9fe1e2a5a and made configurable in d7d10d6a55fc1f048904e8fa001051d71eb1db7b.
