### ISSUE TITLE
Invoking a System Restore in Windows XP will disable Companion

### ISSUE THREAD

**Issue by mhelweg** [reddit-archive/reddit-companion#28]
Due to a completely mangled Visual Studio 2011 Installation I was forced to invoke a "System Restore" and upon returning to my desktop, I attempted to re-install the Reddit companion because it wasn't present any longer in my chrome browser. I would not allow me, saying that it was installed already.
I disabled, and uninstalled the companion without any problems or unexpected events.
I exited and re-started Chrome (13.07.82) and re-installed the Reddit companion and it installed without any issues, but after restarting chrome once again - no reddit companion. I've tried every damn thing including uninstalling chrome which removed all of my extensions and settings, re-installed - unfortunately I got the same result. Companion will not re-engage.

Any thoughts, ideas, half-assed conjectures?

**Comment by chromakode** [comment]
Bizarre! Since I am not a Windows user I'm afraid I don't have much to suggest for this. Closing this bug since it's old and probably specific to Chrome.
