### ISSUE TITLE
Symbols in submission titles are encoded in the bar

### ISSUE THREAD

**Issue by mhweaver** [reddit-archive/reddit-companion#29]
Similar to [issue #14](https://github.com/reddit/reddit-companion/issues/14), if a submission has any encoded symbols in it, they shows incorrectly in the bar (for example, '&' shows as '&amp;').

[Example submission with this problem](http://www.reddit.com/r/movies/comments/ka02e/best_ad_i_ever_saw_for_head_shoulders/)

**Comment by chromakode** [comment]
Fixed in 2feb2d5329d8ae3e84738bb1a7a4849697effcaf. :)
