### ISSUE TITLE
Fuck Off

### ISSUE THREAD

**Issue by boybunny** [reddit-archive/reddit-companion#30]
Reddit is a mob of narcissistic little circle jerkers! You advertise on Reddit, I will NEVER use Chrome on Android again. I am also reconsidering owning an Android tablet because I hate Reddit so fucking much! I have an iPad2, and I will switch to it as my primary machine. Did I mention that REDDIT IS A PACK OF FUCKTARDDS!?

Cancel this account... I have nothing further to say about this, and anyone associated with Reddit is not worth a wipe of my hairy arse!

**Comment by chromakode** [comment]
See ya.
