### ISSUE TITLE
Duplicate subreddit entries (Subreddit Manager)

### ISSUE THREAD

**Issue by ghost** [reddit-archive/reddit-companion#31]
Just happening on one of my computers at this time. 

http://cl.ly/3n2z3N0E38261a223c3K

Dropdown subreddit manager displays duplicate entries. Not sure what troubleshooting information would be relevant here, so let me know.

**Comment by mhweaver** [comment]
The subreddit manager is actually part of the [Reddit Enhancement Suite](https://github.com/honestbleeps/Reddit-Enhancement-Suite) by honestbleeps, not reddit companion (unless companion is conflicting with RES, somehow. Disabling companion temporarily and checking to see if the problem goes away would point to a problem with companion. If it doesn't go away, it's probably not something in companion). It would probably be a good idea to submit a bug report for RES.

**Comment by ghost** [comment]
Umm.. I'm a moron. Thanks.
