### ISSUE TITLE
Companion doesn't log in

### ISSUE THREAD

**Issue by kinnison** [reddit-archive/reddit-companion#37]
I click the 'login' button on the bar when it appears, and it takes me to reddit's sign-in page.  Signing in doesn't then cause companion to show me upvote/downvote and even refreshing the page which prompted the login doesn't help.

Also, now I'm definitely logged into reddit, but companion still only presents me a login button rather than voting buttons.

**Comment by ghost** [comment]
I get this issue too. I have 'Third Party Cookies' blocked, and that might be the problem...

**Comment by chromakode** [comment]
I believe this will be fixed by 8c7130750a3c0bc17b96f0715712726b42abbadd.
