### ISSUE TITLE
Bar not showing for this particular submission

### ISSUE THREAD

**Issue by johnruth** [reddit-archive/reddit-companion#4]
Image Link:  http://i.imgur.com/2079x.jpg
Comments link:  http://www.reddit.com/r/fffffffuuuuuuuuuuuu/comments/ipm25/better_than_most_rage_comics/

Normally, when I click on images (or any post for that matter) the extension bar is displayed at the top of the page over the regular bar.  For this image it doesn't.  When I click the Reddit face in the address bar, it never finds the post and only displays a new submission bar.

**Comment by chromakode** [comment]
This is happening because the url submitted to reddit is "http://imgur.com/2079x.jpg", which imgur redirects to "http://i.imgur.com/2079x.jpg". Unfortunately the extension doesn't track redirects yet. This will be fixed in a future version.
