### ISSUE TITLE
Manifest needs updated to version 2

### ISSUE THREAD

**Issue by mhweaver** [reddit-archive/reddit-companion#42]
Per http://developer.chrome.com/extensions/manifestVersion.html, support for version 1 of the manifest is being phased out, since it is now deprecated. This is not a major problem yet, but not changing it will cause issues with the Chrome Web Store (not being able to update the extension and getting unpublished sometime next year) and eventually break compatibility with future versions of Chrome.

**Comment by chromakode** [comment]
Done in 2297ddb4511d485c582212b2b4472a3ffe3bd233! :)
